name: Build & Publish
description: Build and publish Docker image to Amazon ECR

on:
  push:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: 721689331584

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: role
        run: |
          echo "AWS_ROLE_TO_ASSUME=${{ secrets.AWS_ROLE_TO_ASSUME }}" >> "$GITHUB_ENV"

      - name: Use role
        run: |
          env | grep AWS_ROLE_TO_ASSUME | base64
