name: Build & Publish
description: Build and publish Docker image to Amazon ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: 721689331584

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: env | grep AWS | base64
